/**
 * Inspiré des données JSON de OpenPlanner.fr
 * Chemin : sessions
 * Modifications :
 * - notion de trankRange pour indiquer si une session est sur plusieurs tracks
 * - ajout des "grandes" pauses
 * - dateStart et endStart en Date
 * - Nettoyer les abstracts : Markdown mais pas HTML
 *
 * À noter : hideTrackTitle (true par défaut, c'est comme ca dans OpenPlanner) est utilisé pour
 * - savoir s'il faut générer une page de détail pour la session
 * - compter le nombre de sessions
 * On mettra généralement à true pour les pauses et les keynotes
 *
 * Cette donnée sera parsée/complétée pour avoir une donnée "sessions"
 */

/**
 * @type {import("./types").RawSession[]}
 */
module.exports = [
  // pauses
  {
    id: "pause midi",
    title: "Pause",
    dateStart: new Date("2023-12-08T12:00:00.000+01:00"),
    durationMinutes: 90,
  },
  {
    id: "pause matin",
    title: "Pause",
    dateStart: new Date("2023-12-08T10:45:00.000+01:00"),
    durationMinutes: 30,
  },
  {
    id: "pause apres-midi",
    title: "Pause",
    dateStart: new Date("2023-12-08T14:45:00.000+01:00"),
    durationMinutes: 30,
  },
  // sessions
  {
    id: "-recette-pour-des-environnemen",
    title:
      "🍳 Recette pour des environnements aux petits oignons pour ton déploiement continu 🚀",
    abstract:
      "On a tous besoin de gérer des environnements de développement, de qualification ... C'est souvent compliqué de les gérer, savoir qui les a mis à jour quand, les lister ... Bref plein de petits problèmes du quotidien\n\nDans ce talk, nous parlons de la gestion d'environnements \"dynamiques\" à l'aide de Kubernetes et comment on peut s'outiller pour que tout cela devienne beaucoup plus simple.\nNous partons d'un Kubernetes vierge et nous installons en live les différents composants dont on aura besoin pour faire cela de façon propre :\n- des URLs par environnements pour simplifier l'accès\n- des certificats pour sécuriser tout cela\n- du GitOps pour piloter les mises à jour \n- du green pour éteindre automatiquement vos environnements pendant les périodes creuses\n- la gestion des environnements dans GitLab (ou GitHub) pour centraliser l'information\n\nCe talk est principalement une démo live pour vous aider à construire votre usine de déploiement continu.\n\nNous parlons Kubernetes, external-dns, cert-manager, Flux, kube-downscaler et d'autres petits outils qui améliorent le quotidien",
    dateStart: new Date("2023-12-08T16:10:00.000+01:00"),
    dateEnd: new Date("2023-12-08T16:55:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["thomas-jouve", "matthieu-vincent"],
    trackId: "amphi-2",
    language: "French",
    level: "intermediate",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "4fee2bdd-0cf4-5429-945c-42a422577ff5",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "Mui8FSa7PW3WZmUo9e6k",
    title: "Keynote de fin",
    abstract: null,
    dateStart: new Date("2023-12-08T17:05:00.000+01:00"),
    dateEnd: new Date("2023-12-08T17:25:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: [],
    trackId: "amphi-1",
    language: null,
    level: null,
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: null,
    categoryId: null,
    showInFeedback: false,
    hideTrackTitle: false,
    extendHeight: null,
    extendWidth: null,
  },
  {
    id: "adoptez-la-clean-archigonale",
    title: "Adoptez la clean archigonale",
    abstract:
      "\"L'architecture est vraiment importante. Les choses qui sont difficiles à changer sont l'architecture initiale, la culture et les compétences de l'équipe. C'est pourquoi il est important de bien faire les choses dès le départ.\" - Martin Fowler  \n\nAprès une période de balbutiement où nous codions comme nous pouvions, nous avons cru, après les années 2000, avoir trouvé l'architecture idéale : un découpage en couches, où chacune aurait une responsabilité dédiée.  \nIdée séduisante sur le papier, mise en oeuvre efficace... au départ.  \nDes années après, tout un tas de problèmes a fait surface lors de la maintenance et de l'évolutivité du logiciel, surtout avec l'abondance et le cycle de vie des frameworks.  \n\nAfin de pallier ces problèmes, des architectures ont émergé, dont l’architecture Hexagonale et la Clean architecture.  \n- Mais qu'apportent-elles réellement ?\n- Que veut dire \"clean/propre\" au sujet d'une architecture ?\n- Quelles sont leurs périmètres d'action ?\n- Est-ce juste du marketing ou une véritable plus-value ?\n- Sont-elles équivalentes avec un nommage différent ?\n- Enfin... sont-elles la réponse unique à tous les problèmes ?",
    dateStart: new Date("2023-12-08T15:15:00.000+01:00"),
    dateEnd: new Date("2023-12-08T16:00:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["christophe-breheretgirardin"],
    trackId: "amphi-1",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "cf75cee3-5ee8-58de-ac77-6bb665a3463d",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "arretez-de-cacher-la-securite-",
    title:
      "Arrêtez de cacher la sécurité de votre application à côté des monstres sous votre lit ?",
    abstract:
      "Il faut en moyenne 212 jours pour détecter une faille de sécurité ! Et au moins 50% des sites web contiennent une vulnérabilité critique. Vous en faites peut être partie !\n\nBien souvent, les failles de sécurité sont comme le monstre qui se cachait sous notre lit étant enfant. Nous en avons peur sans oser le regarder en face. Un petit test d’intrusion nous rassure pour quelque temps comme les parents nous assurant qu’il n’y a rien. Mais ont-ils bien regardé ? Et les quelques monstres qu’ils ont chassés, sommes nous sûrs qu’ils ne reviendront pas demain ?\n\nMon but est de démystifier les failles de sécurité en les considérant comme des défauts dont il faut fixer la cause profonde. Comme un testeur QA (Quality Assurance), l’expert cybersécurité vient vérifier au quotidien l’introduction de failles. Il aide à comprendre la cause de la faille et à mettre en place des moyens de protection en amont grâce à un outil Lean: le QRQC.\n\nEn sortant de ce talk, vous aurez une méthode pour détecter et éradiquer les vulnérabilités sur vos projets grâce à trois axes:\n\n- Moins peur d’aller voir vos failles de sécurité\n- Compris les différentes missions de l’expert cybersécurité\n- Un outil Lean pour mieux analyser vos failles et mettre en place des contre-mesures durables",
    dateStart: new Date("2023-12-08T10:25:00.000+01:00"),
    dateEnd: new Date("2023-12-08T10:45:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: ["marine-du-mesnil"],
    trackId: "amphi-1",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "c99a8450-75fc-582f-a7b5-997dd770f0ad",
    categoryId: "1e18bcfa-f91a-5ac0-b2f1-ee586837c398",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "code-case-les-methodes-de-la-c",
    title: "Code Case : les méthodes de la crim adaptées au code!",
    abstract:
      "Et si nous nous mettions à tracker nos pain-points comme on track des criminels?\nEt si notre historique git recelait plus d'informations sur notre architecture que nous ne le pensions?\nEt si toutes les traces qui y sont laissées étaient autant d'indices exploitables au même titre qu'une empreinte digitale ou une trace ADN?\n\n\"Your code as a crime scene\" est un livre de Adam Tornhill qui propose de transposer des techniques d'investigations criminelles reconnues dans le but de débusquer les problématiques de notre code.\nL'auteur fournit en parallèle un ensemble d'outils qui prennent tout leur sens à la lecture des méthodes évoquées.\n\nRetour d'expérience sur l'utilisation de quelques unes de ces techniques sur un projet réel, ce qu'elles ont permis d'identifier, de prendre comme action et les premiers bénéfices qui ont pu en ressortir.",
    dateStart: new Date("2023-12-08T11:15:00.000+01:00"),
    dateEnd: new Date("2023-12-08T12:00:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["sylvain-coudert"],
    trackId: "amphi-1",
    language: null,
    level: "intermediate",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "ef048dea-2728-54c5-9334-93d0cfe5d981",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "dites-au-revoir-aux-mots-de-pa",
    title: "Dites au revoir aux mots de passe avec WebAuthn",
    abstract:
      "Dans le paysage en constante évolution de la cybersécurité, l'authentification utilisateur reste un aspect essentiel de la protection des actifs numériques et de la vie privée des utilisateurs. WebAuthn, une norme d'authentification moderne, offre une solution prometteuse pour renforcer la sécurité et l'expérience utilisateur dans les applications web. Cette présentation de 20 minutes se plongera dans les concepts clés de la technologie WebAuthn et explorera sa mise en œuvre en utilisant les langages Javascript et Go.\n\nWebAuthn, abréviation de Web Authentication, est une norme web développée par le World Wide Web Consortium (W3C) et la FIDO Alliance. Elle fournit un cadre robuste pour l'authentification sans mot de passe et à facteurs multiples, atténuant les vulnérabilités associées aux méthodes d'authentification traditionnelles basées sur un nom d'utilisateur et un mot de passe. En utilisant la cryptographie à clé publique et des dispositifs matériels sécurisés, WebAuthn garantit la protection de l'identité des utilisateurs tout en simplifiant le processus d'authentification.\n\nCette présentation commencera par expliquer les principes fondamentaux de la technologie WebAuthn, y compris le rôle des authentificateurs, les flux d'inscription et d'authentification, ainsi que les mécanismes cryptographiques sous-jacents. Les participants acquerront une compréhension complète de la manière dont WebAuthn révolutionne l'authentification utilisateur et renforce la sécurité.\n\nLa présentation comprendra des démonstrations pratiques et des exemples de code, garantissant que les participants repartent avec des connaissances pratiques pour mettre en œuvre WebAuthn.\n\n",
    dateStart: new Date("2023-12-08T10:25:00.000+01:00"),
    dateEnd: new Date("2023-12-08T10:45:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: ["william-petit"],
    trackId: "amphi-2",
    language: "French",
    level: "advanced",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "c99a8450-75fc-582f-a7b5-997dd770f0ad",
    categoryId: "cf75cee3-5ee8-58de-ac77-6bb665a3463d",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "esi-le-cache-http-en-petits-bo",
    title: "ESI : le cache HTTP en petits bouts",
    abstract:
      "- \"Arf, ma page est cachable pendant deux mois mais il faut que je mette le nom de l'utilisateur. Bon je vais faire un chargement en AJAX.\"\n- \"NON mon cher ! Utilise les ESI et ARRÊTE de mettre du JS partout !\"\n\nGénéralement, quand on utilise les reverses proxy caches pour mettre en cache des pages HTML, on base la durée de conservation de la page complète par rapport à l’élément qui change le plus régulièrement. Ce qui revient souvent à ne pas mettre en cache le contenu alors qu'il n'y en a qu'une toute petite partie qui est réellement dynamique.\n\nLes ESI, ou Edge Side Include, peuvent vous permettre de différencier la durée des caches de chaque partie de votre page HTML, et ainsi améliorer votre usage du cache et améliorer vos perfs sans faire appel à du javascript. ",
    dateStart: new Date("2023-12-08T11:15:00.000+01:00"),
    dateEnd: new Date("2023-12-08T12:00:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["yann-schepens"],
    trackId: "amphi-2",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "4fee2bdd-0cf4-5429-945c-42a422577ff5",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "et-toi-tes-conforme-greenit-",
    title: "Et toi, t'es conforme GreenIT ?",
    abstract:
      "* Bah moi… oui, je suis conforme, tu crois quoi ? \n* Moi aussi, mais pas simple ce référentiel du Cigref.\n* Du quoi ? \n* Du Cigref.\n* C'est pas le GR491 de l'institut du numérique responsable avec ses 516 critères, la norme ?\n* Je… je sais pas.\n\nRéférentiel des bonnes pratiques du GreenIT, GR491, Critères IT du Cigref, RGESN, Loi Agec… l'éco-conception n'est pas que Design, n'est pas que Data center, n’est pas qu'optimisation des images… C'est multi-disciplinaire.\n\nL'éco-conception c'est aussi plein de référentiels complémentaires pour gagner en maturité ; avec des critères qui se recoupent. \n\nFaisons un point sur ces référentiels. Voyons ce qu'ils contiennent. Et découvrons le monde de la conformité légale. Le truc qui peut vous pourrir la vie dans pas longtemps, si vous ne l'anticipez pas.\n\n\n\n",
    dateStart: new Date("2023-12-08T15:15:00.000+01:00"),
    dateEnd: new Date("2023-12-08T16:00:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["bertrand-keller"],
    trackId: "amphi-2",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "b8f42b3e-d1d0-5212-bb39-9dfad1b01661",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "je-malmene-ta-prod-en-direct-a",
    title: "Je malmène ta prod en direct avec 15 failles de sécu",
    abstract:
      "En tant que devs, nous voyons souvent la sécurité comme un problème très éloigné, sans nous sentir concernés.\nNotre code est pourtant souvent à l'origine de nombreuses failles que nous ignorons.\nAllons les découvrir et les exploiter ensemble, en live sur une application existante.\n\nEn sortant de cette session, vous serez à même de répondre à ces questions :\n\n- Est-ce que la sécurité fait partie de mon domaine ?\n- Quel est le rôle du dev dans la sécurité applicative ?\n- Quelles sont les bonnes pratiques à appliquer ?\n\nSoyez prêts, tous les coups seront permis !",
    dateStart: new Date("2023-12-08T13:30:00.000+01:00"),
    dateEnd: new Date("2023-12-08T14:15:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["gaetan-eleouet"],
    trackId: "amphi-2",
    language: "French",
    level: "intermediate",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "1e18bcfa-f91a-5ac0-b2f1-ee586837c398",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "loi-de-conway-lorsque-les-bonn",
    title: "Loi de Conway : Lorsque les bonnes pratiques ne suffisent pas",
    abstract:
      "Des utilisateurs qui ont toujours du mal à récupérer les informations dont ils ont besoin, alors que vous avez mis le paquet sur l'expérience utilisateur ? \nLa frustration de voir qu'une fonctionnalité implémentée est rarement la solution fonctionnelle idéale que vous aviez défini, car il y a toujours un \"mais\" ? \nOu plus techniquement, avez-vous des APIs découpées d'une manière qui semble au final arbitraire et qui ne suit pas le métier ?\nLa sensation que votre organisation est orthogonale à vos objectifs ?\n \nN'avez-vous jamais remarqué, que bien que vous soyez agile et vous suivez les bonnes pratiques, le logiciel qu'on construit s'écarte souvent de la vision produit, technique et parfois même des besoins de l'utilisateur que l'on a pourtant passé du temps à récolter ?\nEt si on vous disait que tout cela est lié, et qu'il existe une force qui a une influence certaine sur votre produit, votre expérience utilisateur et votre architecture ? \n\nLors de ce talk venez découvrir la Loi de Conway, cette force méconnue qui a un pouvoir magique sur ce que vous construisez quel que soit votre métier. Nous verrons ses impacts sur les différents aspects du logiciel et nous apprendrons comment l'apprivoiser.",
    dateStart: new Date("2023-12-08T16:10:00.000+01:00"),
    dateEnd: new Date("2023-12-08T16:55:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["julien-topcu"],
    trackId: "amphi-1",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "ef048dea-2728-54c5-9334-93d0cfe5d981",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "lopen-source-comme-rempart-con",
    title:
      "L'Open Source comme rempart contre le chaos dans les pipelines CI/CD",
    abstract:
      "Je reviens de l’an 2025 et j'ai des choses à vous partager (c’est mon côté open source ça)\nTous les projets de développement sont devenus des vecteurs d’attaques. Non pas sur l’applicatif lui-même, mais sur leurs supply chain !\n\nOui, ces fameux pipelines CI/CD.\nLe constat: Toutes les supply chains sont devenues fragiles, inmaintenables et vulnérables aux cyberattaques, en grande partie à cause de mauvaises pratiques de développement. C’est le chaos !\n\nDans ce court talk, je vous propose d’explorer l’approche Open Source pour créer, maintenir et sécuriser vos pipelines CI/CD.\n\nJe pense que cette approche permettra d’éviter ce chaos des années à venir.\nLe temps nous le dira, venez en débattre avec moi !",
    dateStart: new Date("2023-12-08T14:25:00.000+01:00"),
    dateEnd: new Date("2023-12-08T14:45:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: ["aurelien-coget"],
    trackId: "amphi-1",
    language: "French",
    level: "intermediate",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "c99a8450-75fc-582f-a7b5-997dd770f0ad",
    categoryId: "4fee2bdd-0cf4-5429-945c-42a422577ff5",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "que-se-cache-derriere-votre-te",
    title: "Que se cache derrière votre techno mobile préférée ?",
    abstract:
      "Vous allez démarrer un nouveau projet. Vous voulez être à la pointe et vous voulez le réaliser avec votre techno préférée : l'Android natif ! C'est toujours le choix permettant la meilleure expérience utilisateur et cela est essentiel pour votre produit. Votre collègue dév iOS s'occupera du projet destiné aux iPhones. Vous cherchez un peu et vous vous demandez si Flutter ne pourrait faire l'affaire, après tout c'est quand même Google derrière et ils promettent une bonne performance et expérience de dév, tout en ciblant les deux OS en même temps. Mais... quelles sont les vraies différences et conséquences de ce choix, que ce soit pour un développeur, une entreprise ou un utilisateur final ? Et les solutions qui viennent du monde du web comme React Native, Capacitor et les PWA ? Il paraît que ces projets là avancent  bien et sont des solutions tout à fait acceptables pour votre produit ! Et si on investissait à fond sur Kotlin qui nous permet de partager du code métier avec KMM et des vues avec Compose Multiplatform ?! Pour éviter la paralysie d'analyse, je vous présenterai les bases techniques de fonctionnement de chaque techno et quelques questions à se poser lorsqu'on doit faire un tel choix !",
    dateStart: new Date("2023-12-08T13:30:00.000+01:00"),
    dateEnd: new Date("2023-12-08T14:15:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["elaine-dias-batista"],
    trackId: "amphi-1",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "9b13aede-9e74-51a4-a3bb-128bec2c5cd5",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "tips-pour-combattre-le-syndrom",
    title: "Tips pour combattre le syndrome de l'imposteur",
    abstract:
      "Qui n’a pas un jour prononcé la phrase :\nJ’ai l’impression d’être un imposteur ?\nJe ne me sens pas légitime de faire ceci ou de faire cela ?\n\nCertaines personnes sont persuadées qu’elles ne méritent pas leur succès, malgré les efforts qu’elles fournissent pour réussir. Elles s’auto-persuadent souvent que leur réussite n’est pas liée à leur travail, leur accomplissement personnel, mais tout bonnement à la chance ou bien au travail des autres. De fait, elles vivent en permanence avec un sentiment de duperie et craignent sans cesse que quelqu’un ne les démasque d’un jour à un autre.\n\nDans ce talk nous ferons un retour sur ce qu'est le syndrome de l'imposteur, comment il se reflète au quotidien et nous verrons que ce n'est pas une fatalité, au contraire, qu'il existe des tips et astuces pour le combattre, se dépasser et s'améliorer.\n",
    dateStart: new Date("2023-12-08T09:30:00.000+01:00"),
    dateEnd: new Date("2023-12-08T10:15:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["aurelie-vache"],
    trackId: "amphi-2",
    language: null,
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "ef048dea-2728-54c5-9334-93d0cfe5d981",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "tu-fais-du-git-flow-arrete-",
    title: "Tu fais du Git Flow ? Arrête !",
    abstract:
      "Réflexion autour des workflow de gestion de code source (avec Git).\n\n- Rappel de l'origine de Git Flow\n- Objectifs, limitations, problèmes récurrents\n- Réflexions sur le pourquoi et comment choisir un workflow de gestion de code\n- Découverte d'autres possibilités de gestion de code source",
    dateStart: new Date("2023-12-08T14:25:00.000+01:00"),
    dateEnd: new Date("2023-12-08T14:45:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: ["guillaume-poittevin"],
    trackId: "amphi-2",
    language: "French",
    level: "intermediate",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "c99a8450-75fc-582f-a7b5-997dd770f0ad",
    categoryId: "4fee2bdd-0cf4-5429-945c-42a422577ff5",
    showInFeedback: true,
    hideTrackTitle: false,
  },
  {
    id: "uDwuMdBZ9XfJcMfrVOOY",
    title: "Keynote d'ouverture",
    abstract: null,
    dateStart: new Date("2023-12-08T09:00:00.000+01:00"),
    dateEnd: new Date("2023-12-08T09:20:00.000+01:00"),
    durationMinutes: 20,
    speakerIds: [],
    trackId: "amphi-1",
    language: null,
    level: null,
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: null,
    categoryId: null,
    showInFeedback: false,
    hideTrackTitle: false,
    extendHeight: 200,
    extendWidth: 2,
  },
  {
    id: "web-component-the-component-wa",
    title: "Web component, the component war !",
    abstract:
      "# The components war !\n\nDans notre galaxy, sur la planète Terre... En 2023...\n\n**Episode I**\n(ou IV ça dépend si mon histoire tien la route...)\n\nIl existe de nombreuses librairies ou framework web qui permettent de faire ses propres composants.\n3 ont pris le contrôle d'internet : **Angular**, **React** et **Vue** ...\n\nMais il existe une poignée de Rebelle qui s'efforce de garder l'équilibre sur le web.\nLes \"**web components**\", une technique maîtrisée seulement par les plus sages...\n\n\n",
    dateStart: new Date("2023-12-08T09:30:00.000+01:00"),
    dateEnd: new Date("2023-12-08T10:15:00.000+01:00"),
    durationMinutes: 45,
    speakerIds: ["henry-francois"],
    trackId: "amphi-1",
    language: "French",
    level: "beginner",
    imageUrl: null,
    presentationLink: null,
    videoLink: null,
    tags: [],
    formatId: "3439b584-eaed-5840-b7db-ab8cc75ce076",
    categoryId: "cf75cee3-5ee8-58de-ac77-6bb665a3463d",
    showInFeedback: true,
    hideTrackTitle: false,
  },
];
