/**
 * Inspiré des données JSON de OpenPlanner.fr
 * Chemin : sessions
 * Modifications :
 * - notion de trackRange pour indiquer si une session est sur plusieurs tracks
 * - ajout des "grandes" pauses
 * - dateStart en Date
 * - pas de endStart
 * - Nettoyer les abstracts : Markdown mais pas HTML
 *
 * À noter : hideTrackTitle (false par défaut, c'est comme ca dans OpenPlanner) est utilisé pour
 * - savoir s'il faut générer une page de détail pour la session
 * - compter le nombre de sessions
 * On mettra généralement à true pour les pauses et les keynotes
 *
 * Cette donnée sera parsée/complétée pour avoir une donnée "sessions"
 */

/**
 * @type {import("./types.js").RawSession[]}
 */
export default [
  // pauses
  {
    id: "pause matin",
    title: "Pause",
    dateStartStr: "2026-12-04T10:55:00.000+01:00",
    durationMinutes: 20,
    trackRange: ["jardins-de-la-tour", "forge"],
    styleClass: "pause",
    hideTrackTitle: true,
  },
  {
    id: "pause midi-atelier",
    title: "Pause repas",
    dateStartStr: "2026-12-04T12:30:00.000+01:00",
    durationMinutes: 30,
    trackRange: ["jardins-de-la-tour", "scriptorium"],
    styleClass: "pause",
    hideTrackTitle: true,
  },
  {
    id: "pause midi-commun",
    title: "Pause repas",
    dateStartStr: "2026-12-04T13:00:00.000+01:00",
    durationMinutes: 65,
    trackRange: ["jardins-de-la-tour", "forge"],
    styleClass: "pause repas-commun",
    hideTrackTitle: true,
  },
  {
    id: "pause midi",
    title: "Pause repas",
    dateStartStr: "2026-12-04T14:05:00.000+01:00",
    durationMinutes: 25,
    trackRange: ["tour-des-arcanes", "forge"],
    styleClass: "pause",
    hideTrackTitle: true,
  },
  {
    id: "pause apres-midi",
    title: "Pause",
    dateStartStr: "2026-12-04T16:15:00.000+01:00",
    durationMinutes: 20,
    trackRange: ["tour-des-arcanes", "forge"],
    styleClass: "pause",
    hideTrackTitle: true,
  },
  {
    id: "pause apres-midi-atelier",
    title: "Pause",
    dateStartStr: "2026-12-04T16:20:00.000+01:00",
    durationMinutes: 15,
    trackRange: ["jardins-de-la-tour", "scriptorium"],
    styleClass: "pause",
    hideTrackTitle: true,
  },
  // keynotes
  {
    id: "keynote-fin",
    title: "Remerciements et clôture de la journée",
    dateStartStr: "2026-12-04T17:55:00.000+01:00",
    durationMinutes: 10,
    hideTrackTitle: true,
  },
  // tremplin
  {
    id: "tremplin-1",
    title: "Talk issu du Tremplin du DevFest Dijon",
    abstract: "_Informations à venir…_",
    dateStartStr: "2026-12-04T12:10:00.000+01:00",
    durationMinutes: 20,
    speakerIds: [],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
    hideTrackTitle: true,
  },
  {
    id: "tremplin-2",
    title: "Talk issu du Tremplin du DevFest Dijon",
    abstract: "_Informations à venir…_",
    dateStartStr: "2026-12-04T12:10:00.000+01:00",
    durationMinutes: 20,
    speakerIds: [],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
    hideTrackTitle: true,
  },
  // conférences
  {
    id: "DsxCS78g4rtSz8vKtGSm",
    title:
      "De villageoise à l’IT Woman … Quelles actions pour faire de mon rêve TECH une réalité ?",
    abstract:
      "Venue d'ailleurs, fille d'analphabètes, surmontant des obstacles : préjugés, patriarcat, inégalités sociales, racisme, sexisme …\n\nDe orpheline à l'écolière, du théâtre au chronique radio, de l'engagement à l'action, de la série de mon enfance (24h chrono) au double diplôme d'ingénieur Tech (DEV & DATA), j'ai toujours su bien m'entourer et aller de l'avant.\n\nJe suis Houleymatou Baldé, co-fondatrice d'IT Woman Movement, conférencière professionnelle et Lead Tech chez NovoDev, un éditeur de logiciel.",
    dateStartStr: "2026-12-04T08:00:00.000+00:00",
    durationMinutes: 60,
    speakerIds: ["GApOTPqDfIwafBVZpi27"],
    trackRange: ["jardins-de-la-tour", "forge"],
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
    hideTrackTitle: false,
    styleClass: "keynote",
  },
  {
    id: "cmnzwk78y00ny01o2e0fmnmp5",
    title: "Le seigneur du legacy, la communauté du code",
    abstract:
      "Un code pour les gouverner tous, un code pour les lier...\"\nAvez-vous déjà hérité d'un projet avec un fichier marqué \"NE PAS TOUCHER\" ?\n\nAvez-vous déjà vécu une réunion d'architecture de 4 heures qui n'aboutit à rien ?\n\nAvez-vous déjà vu un projet où corriger un bug en introduit plusieurs autres ?\n\nSi oui, cette présentation est pour vous !\n\nÀ travers le prisme épique du Seigneur des Anneaux, nous explorerons les défis quotidiens du développement logiciel : le couplage fort qui corrompt nos systèmes comme l'Anneau Unique et la dette technique qui s'accumule telle une armée d'Orques.\n\nCette conférence s'adresse aux développeurs, architectes, et managers qui ont vécu (ou vivront bientôt) les péripéties du legacy code.\n\nJe vous y partagerai une vision sur le couplage, la dette technique et quelques techniques pour écrire du code plus facile à maintenir.",
    dateStartStr: "2026-12-04T16:00:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmnzwk78m00nx01o2e0mjq9l7"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmo17ykdd00rd01o2v03x0eor",
    title: "Je malmène ton LLM en direct avec 10 failles de sécurités",
    abstract:
      "Les LLM sont à la mode, et soulèvent eux aussi des problèmes de sécurité.\n\nNous en avons pourtant mis dans nos applications, sans nous sentir concernés.\n\nNotre code est pourtant souvent à l'origine de nombreuses failles que nous ignorons.\nAllons les découvrir et les exploiter ensemble, en live sur une application existante.\nEn sortant de cette session, vous serez à même de répondre à ces questions :\n- Qu'est-ce que qu'une faille de sécurité pour un LLM ?\n- Quel est le rôle de l'équipe de dev dans la sécurité ?\n- Quelles sont les bonnes pratiques à appliquer ?\n\nSoyez prêts, tous les coups seront permis !",
    dateStartStr: "2026-12-04T10:15:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmo17ykd400rc01o2ujfy5t8t"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmo3eswq100zl01o2pd4qsc7j",
    title:
      "Ma relation toxique avec l'IA : le piège du context engineering infaillible",
    abstract:
      "Je dois crier sur mon IA pour qu'elle utilise le bon contexte à chaque fois.\n\nJ'ai ajouté 15 \"MANDATORY\" en majuscules dans mes skills.\nJ'ai soumis 10 fois le même prompt, pour voir si ma skill se déclenchait systématiquement.\nEt à chaque manquement, je poussais un commit pour \"l'ajuster\".\n\nJe ne voulais pas une IA utile. Je voulais une IA **infaillible**.\n\nJe suis cette personne en couple qui exige la perfection absolue.\n\nUne erreur ? Impardonnable.\nJe veux du déterminisme.\n\nJe suis dans une **relation toxique avec l'IA**.\n\nEt cette toxicité m'a coûté du temps, de l'énergie… et beaucoup trop de commits.\n\nDans ce talk, je raconte l'histoire de cette relation en trois actes :\n- **La lune de miel** (10 min) — L'enthousiasme de l'early adopter et les promesses du context engineering\n- **La control freak** (15 min) — L'obsession du contexte parfait, les 15 \"MANDATORY\" en majuscules\n- **La thérapie de couple** (15 min) — Le déclic : on peut optimiser son contexte plus sainement. Et l'IA n'est pas une télécommande déterministe, mais un partenaire d'itération qui me rend déjà 3x plus productive\n\nJe vous montrerai des extraits de skills toxiques, les diffs successifs de ma PR obsessionnelle et la version saine, efficace et maintenable.\n\nA la fin de ce talk, vous repartirez avec :\n- **Des exemples de fichiers de contexte qui marchent** — et ceux qui sabotent\n- **Les signaux d'alerte de l'over-engineering** — quand vos \"MANDATORY\" deviennent contre-productifs\n- **Des bonnes pratiques hors fichiers de contexte** — choisir le bon mode d'interaction, gérer la fenêtre de contexte\n- **Un mindset réaliste** — même avec des loupés, un contexte bien calibré reste un atout précieux pour construire du code propre et livrable plus rapidement\n\n---\n\n**PLAN DETAILLE** du talk disponible en dépliant les Références ci-dessous\n\n---",
    dateStartStr: "2026-12-04T13:30:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmo3eswpp00zk01o25d7f0w9h"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e401pf7z4ohrha",
  },
  {
    id: "cmoa7vcqg00kq01mkofw2xi47",
    title:
      'Ce que les développeurs "haut niveau" peuvent (re)apprendre des dev embarqués',
    abstract:
      'Nous, développeurs embarqués sommes un peu "ostracisés" par les autres développeurs utilisant des langages plus "haut niveau"...\nBeaucoup se demandent encore pourquoi nous restons encore à l\'âge de pierre avec nos vieux outils et nos vieilles pratiques...\n\nPourtant de nombreuses pratiques perçues comme "nouvelles" comme l\'écoconception, les principes de simplicité du design (KISS) et l\'optimisation/refactoring réguliers... sont des pratiques issues des nécessités des environnements contraints sur lesquels nous développons (et que les développeurs haut niveau ont malheureusement oubliées).\n\nIl est peut être temps de réapprendre de nos "anciens" certaines bonnes pratiques...',
    dateStartStr: "2026-12-04T13:30:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmoa7vcqa00kp01mkmbfpgeam"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmog1d7jn002b01o23pu8a17d",
    title:
      "Le plus dur, c'est de commencer... Le fun de galérer sur un projet perso",
    abstract:
      "Vous hésitez à vous lancer dans un projet perso ? Venez sourire (et apprendre) avec mon retour d’expérience 100% authentique : de l’architecture hexagonale au déploiement en passant par la conception produits et les tests, je vous prouve qu’on peut construire un produit de A à Z sans tout maîtriser… et que c’est justement là que ça devient passionnant !\n\nAu programme : Kotlin, Vue.js, GitLab CI, bases de données, reverse proxy, CORS, Scaleway Cloud, doughnut produit et une touche d’IA – le tout saupoudré d’erreurs, de doutes, et d'imperfections. Spoiler : la prod tient toujours debout (enfin, pour l'instant).\n\nL’objectif ? Vous donner l’envie de vous lancer, sans peur des détours. Parce que le meilleur moyen de comprendre ce qu'il se passe sur l'ensemble d'un projet, c'est d'en faire l'expérience.",
    dateStartStr: "2026-12-04T16:00:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmog1d7ji002a01o27sy3bxke"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmogz4f50005j01o29j1ylzyd",
    title: "Heroes : Save the token, save the world",
    abstract:
      "Dans un monde où chaque requête à un LLM consomme de l’énergie, du temps et de l’argent, une question se pose : et si optimiser ses tokens devenait un super-pouvoir ?\n\nInspiré de la série Heroes et de sa réplique culte “Save the cheerleader, save the world”, ce talk propose une nouvelle orientation pour sauver la planète.\n\nPas de théorie abstraite, nous parlons du quotidien des développeurs : comment générer du code avec un LLM sans exploser son budget tokens ou stock de café, et continuer à travailler même quand le LLM est down.\nÀ travers une série de techniques allant du quick win immédiat à une évolution plus profonde des pratiques, nous verrons comment :\n* Améliorer ses prompts et structurer ses échanges pour éviter les allers-retours inutiles\n* Naviguer intelligemment entre les modèles\n* Structurer la stack outil pour optimiser les dépendances tooling (MCP, CLI, Agents, Skills, Plugins...)\n* Tirer parti du caching, des embeddings ou autres\n* Et même, quand c’est pertinent, passer sur son LLM local\n\nLe vrai enjeu ? Faire évoluer sa DevX à travers son setup de développement : outils, habitudes, feedback loops… pour devenir token-efficient by design.\n\nUn talk pragmatique, avec des exemples concrets, quelques fails bien réels, et une bonne dose de pop culture, pour aider chaque dev à reprendre le contrôle.\nParce qu’au final, optimiser ses tokens, ce n’est pas seulement faire des économies, c’est une compétence clé pour coder efficacement à l’ère des LLM.\nEt peut-être, au passage… éviter de tuer quelques arbres.",
    dateStartStr: "2026-12-04T16:00:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmogz4f4v005i01o20ozzp9s0", "cmogz4f4s005h01o2wusrxu8m"],
    trackId: "scriptorium",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e101pffzx6q0qu",
  },
  {
    id: "cmol8q72e006501oh1j8rof2r",
    title:
      "🎤 Qui est veut être Dev !? — le matchmaking startup x tech qui change la donne",
    abstract:
      "Inspiré de Qui veut être mon associé ?, ici, les entrepreneurs pitchent… pour séduire un futur associé tech 💻\n\nLe concept ?\nMettre en relation des startups en quête de développeurs avec des profils techniques à l’esprit entrepreneurial, prêts à s’engager dans une aventure ambitieuse. L’objectif : créer des rencontres à fort potentiel, là où naissent les meilleures équipes.\n\nPourquoi participer ?\n\n💡 Découvrir des projets concrets où ton expertise tech fait vraiment la différence\n🚀 T’impliquer dans une aventure entrepreneuriale, en tant que futur CTO ou cofondateur\n🧠 Challenger des idées, poser tes questions, et voir ce qui te donne envie de builder\n😄 Vivre un format dynamique, sans pression — tu explores, tu échanges, tu choisis\n\nParce qu’un bon produit, c’est avant tout une bonne équipe.",
    dateStartStr: "2026-12-04T10:15:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmol8q71l006401ohp3x3w8ts"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
  },
  {
    id: "cmolzu7xv000u01ofv98r71na",
    title: "On met son ego de coté",
    abstract:
      "L'egoless programming (programmation sans ego) est une méthodologie de développement logiciel prônant la collaboration et la critique constructive pour améliorer la qualité du code. L'idée principale est que le code appartient à l'équipe, pas à un individu, ce qui permet aux développeurs d'accepter plus facilement les suggestions et les modifications sans se sentir personnellement attaqués. \n\nCette session permettra aux développeurs de :\n* Découvrir chacun des 10 commandments, avec des mises en oeuvre\n* Trouver le comportement à avoir en fonction de la position de certains collègues\n* Apprendre à mieux travailler en équipe\n\n\nPourquoi cette présentation ?\nDans un domaine où la complexité technique ne cesse de croître et où l'individualisme peut parfois freiner la progression collective, l'Égoless Programming offre une philosophie éprouvée pour construire des équipes plus résilientes, innovantes et performantes. Il s'agit de dépasser les barrières de l'ego pour favoriser une culture de confiance, de partage et d'amélioration continue. Cette approche, centrée sur l'humain, est plus que jamais nécessaire pour naviguer les défis techniques et relationnels du développement logiciel moderne.\n\nPour qui ?\n* Développeurs juniors et seniors, \n* Architectes,\n* Tech leads \nElle est particulièrement pertinente pour ceux qui cherchent à améliorer la dynamique de leurs équipes, \nL'approche pédagogique basée sur des cas pratiques permettra aux participants de comprendre immédiatement chacun des commandements.",
    dateStartStr: "2026-12-04T09:05:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmolzkx99000f01oflje7pj27", "cmolzkx93000e01ofhgo22jaq"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmor55okx000h01mmpkk59g3p",
    title: "Maternité dans la tech : Du témoignage à l’action",
    abstract:
      "Le manque de parité entre hommes et femmes dans le secteur de la tech est un constat largement partagé. Pour y remédier, anticiper et comprendre les besoins des femmes constitue un véritable atout pour mieux les recruter et les fidéliser. À travers mon expérience de femme enceinte, je propose des stratégies concrètes permettant aux entreprises d’accompagner les femmes pendant et après leur congé maternité.\nNous aborderons les défis spécifiques rencontrés dans la tech, ainsi que des solutions pratiques telles que la création d’espaces sécurisés et de communautés de parents, une communication forte des leaders pour briser les tabous, et des processus RH clairs. Nous explorerons également les pratiques pour un retour au travail réussi : planification de carrière, programmes de mentorat et intégration progressive. Enfin, nous identifierons des leviers d’amélioration comme l’allongement du congé paternité, la formation des managers et la remise en question du présentéisme.\nCette intervention s’adresse particulièrement aux managers techniques, équipes RH et People, ainsi qu’aux développeurs, car chacun a un rôle à jouer pour bâtir un environnement inclusif et durable.",
    dateStartStr: "2026-12-04T15:35:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmor55okq000g01mmsl26byb8"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
  },
  {
    id: "cmotx4dkx009601pxhgq3v8my",
    title:
      "Quand l’accessibilité rencontre le Mob : pratiquer, tester, corriger ensemble",
    abstract:
      "Les ateliers d’accessibilité remplissent rarement les salles, et les conférences sur l’accessibilité numérique restent souvent théoriques : on parle du “pourquoi”, rarement du “comment”.\n\nDans cet atelier, nous allons changer ça.\n\nLe manque de pratique empêche les développeurs et développeuses de progresser. Tester un site avec un lecteur d’écran ou au clavier paraît complexe. Pourtant, il existe des méthodes simples pour apprendre ensemble.\n\nPendant l’atelier, nous corrigerons en direct un site e-commerce volontairement inaccessible, en mob programming. Nous expérimenterons les tests, les outils et les corrections pas à pas.\n\nQue vous soyez dev front, dev généraliste ou novice en accessibilité, vous repartirez avec :\n\n- une méthode pour pratiquer l’accessibilité numérique en équipe\n- une vision concrète de “ce qui compte vraiment”\n- et la preuve que démarrer l’accessibilité, ce n’est pas si compliqué\n\nNB : pensez à apporter vos écouteurs pour écouter le lecteur d’écran. Si vous êtes une personne sourde ou malentendante ou si vous n’avez pas d’écouteurs, vous pourrez activer la visionneuse de paroles qui transcrira ce que dit le lecteur d’écran.",
    dateStartStr: "2026-12-04T13:30:00.000+00:00",
    durationMinutes: 110,
    speakerIds: ["cmotx4djo009401pxkmjo51pq", "cmotx4dk6009501pxf28dz4m4"],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dw01pfktyb71ph",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmowgsi6600fi01o8bgv4t4cr",
    title: "Git : le super-héros mal aimé de ton repo",
    abstract:
      "On utilise Git tous les jours… sans vraiment le connaître. Après tout, ce n’est pas notre cœur de métier : on code, et Git est juste censé suivre. Sauf que parfois, une commande ratée et tout part en cacahuète : historique qui s’emmêle, branches qui se perdent, merge qui tourne au cauchemar… et quelques cheveux blancs en bonus.\n\nPourtant, derrière ces moments de panique se cache un allié puissant, capable de rendre notre quotidien bien plus simple.\n\nDans cette session, nous irons explorer une petite partie des possibilités de Git :\n- voyager entre branches sans se perdre,\n- remonter le temps dans l’historique,\n- restaurer un état précis,\n- dompter les merges capricieux,\n- automatiser les tâches rébarbatives,\n- … et bien plus encore !\n\nVous repartirez avec des astuces concrètes, faciles à appliquer, pour transformer Git en véritable partenaire de sérénité plutôt qu’en source d’angoisse.",
    dateStartStr: "2026-12-04T14:25:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmowgsi5z00fh01o8k551hre3"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmp6lcfgf002e01lfjombazp8",
    title: "Le bon chasseur, le mauvais chasseur, et le bon test",
    abstract:
      "*\"Le mauvais chasseur, il voit un truc qui bouge, il tire. Le bon chasseur, il voit un truc qui bouge, il tire… mais c'est un bon chasseur.\"*\n\nLe mauvais test, il assert un truc, il passe au vert. Le bon test, il assert un truc, il passe au vert… mais c'est un bon test.\n\n- Concrètement, qu'est-ce qui sépare les deux ? \n- Pourquoi certaines suites de tests deviennent un harnais qui permet de refactorer en confiance, et d'autres un boulet qu'on désactive au premier sprint chargé ?\n\n**La promesse**\nUne vraie base de code : les chasseurs du Bouchonnois et leurs parties de chasse aux galinettes qu'on va reprendre ensemble. \nÀ chaque chapitre, un symptôme, un diagnostic, un remède.\n- **Chapitre 1 : Le bon test ne ment pas.** \n   Mutation testing : faire la chasse aux assertions qui passent toujours, parce que *\"never trust a test you haven't seen fail\"*.\n- **Chapitre 2 : Le bon test, on le lit.** \n   Test Data Builders, Object Mothers, custom assertions, DSL Given/When/Then : transformer un test de 30 lignes en spec métier lisible en 5 secondes.\n- **Chapitre 3 : Le bon test, on le maintient.** \n   SRP, DRY, hiérarchie de classes : les principes Clean Code s'appliquent aux tests autant qu'au code de prod.\n- **Chapitre 4 : Le bon test, parfois, ne s'écrit pas à la main.** \n   Approval Testing pour les scénarios à grosses assertions et ses pièges.\n- **Chapitre 5 : Le bon test couvre ce que tu n'as pas pensé à tester.** \n   Property-Based Testing : une propriété, 100 exécutions, des cas tordus que tu n'aurais jamais imaginés.\n- **Chapitre 6 : Le bon test protège l'architecture.** \n   Tests d'architecture : matérialiser les règles d'oignon, d'hexagonal, de Clean Architecture en tests qui échouent au premier merge incorrect.\n\n**Pour qui ?**\nDéveloppeur·se·s, tech leads, toute personne qui a déjà soupiré devant un fichier de tests de 900 lignes. \nDes exemples concrets transposables à tous les langages.",
    dateStartStr: "2026-12-04T10:15:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmnzy3p5j00o401o2zbrazim9"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmpaxsd6n009901p103oo03ai",
    title: 'Tuez votre README : l\'onboarding en un "cd"',
    abstract:
      "« Bienvenue dans la team ! Pour le setup de ton poste : suis le README. Ah, par contre ignore la section 3 : c'est plus à jour. » - un air de déjà-vu ? Les documents d'onboarding de 3km, ça vous parle ? Le classique « ça fonctionne sur ma machine » (mais pas sur la vôtre) vous irrite ?\n \nEt s'il vous suffisait d'une commande, voire même d'un simple `cd`, pour que votre compilateur, vos outils de lint, et vos dépendances système apparaissent comme par magie ? Impossible dites-vous ?\n \nÀ travers cette session, riche en exemples concrets, nous explorerons comment Nix et sa galaxie d'outils (Devbox, Devenv, Flox, Direnv) permettent de construire des environnements de développement hermétiques et déclaratifs en quelques minutes. Si Nix ne vous dit rien, pas d'inquiétude : une brève introduction vous donnera toutes les clés pour ne pas être perdus.\n \nVous repartirez avec des solutions pratiques pour simplifier l'onboarding, améliorer le travail en équipe, et faire en sorte que le « ça fonctionne sur ma machine » soit transformé en « ça marche partout ».",
    dateStartStr: "2026-12-04T09:05:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmpaxsd6h009801p10h2u5h03"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00dz01pf4xodlt41",
  },
  {
    id: "cmpbdh47a00is01p1aatl7r9v",
    title: "Souveraineté numérique, quelles solutions pour quels enjeux ?",
    abstract:
      "La souveraineté numérique devient un enjeu de plus en plus important dans un monde géopolitiquement instable, notamment lorsque le cloud devient la norme.\n\nDans ce talk nous aborderons : \n* Les enjeux autour de la souveraineté et les risques associés\n* Les pilliers de la souveraineté numérique (données, opérations, technologies)\n* Un panorama des produits et technologies pour répondre au mieux à ces risques",
    dateStartStr: "2026-12-04T13:05:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmou6gf3900by01pxbce5cxr6"],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00dz01pf4xodlt41",
  },
  {
    id: "cmpduoc1p015101p1dfvzjoks",
    title:
      "La forge logicielle comme produit interne : pourquoi vos devs sont vos vrais clients",
    abstract:
      "Dans beaucoup d’organisations, la forge logicielle est vue comme un socle technique :\nGit, CI/CD, registry, sécurité, Kubernetes… et débrouillez-vous avec ça.\n\nRésultat ?\n- des pipelines contournés,\n- des outils sous-utilisés,\n- des équipes frustrées,\n- et une plateforme qui évolue au rythme des incidents, pas des besoins.\n\nEt si le problème n’était pas technique ?\n\nCe talk propose un changement de perspective :  \n**et si la forge logicielle était un produit interne**, avec :\n- des utilisateurs (les développeurs),\n- une roadmap,\n- des choix UX,\n- et des arbitrages assumés.\n\nÀ travers des retours d’expérience concrets, nous verrons comment appliquer une vraie approche produit à une forge logicielle pour créer une plateforme utile, adoptée… et aimée (ou au moins respectée).",
    dateStartStr: "2026-12-04T16:00:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmpduoc1g015001p12211uh04"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00dz01pf4xodlt41",
  },
  {
    id: "cmpjq82as007h01mn9zowe8w0",
    title:
      "Le bug n'est pas dans le code ! J'ai enfin compris pourquoi 50% des femmes quittent la tech avant 35 ans",
    abstract:
      "Selon les statistiques, une femme sur deux quitte la tech avant 35 ans. Est ce une fatalité ? Non, je ne crois pas ...\nCette année, je soufflerai ma 34ᵉ bougie, et cela fait 10 ans que je suis ingénieure en développement logiciel.\n\nAussi loin que je me souvienne — jusqu’aux classes de primaire — j’ai toujours aimé les sciences. Les mathématiques, la logique, la résolution de problèmes… tout cela a toujours été une passion. Et pendant longtemps, j’ai cru que cette passion suffirait à me protéger, qu’elle serait un rempart naturel contre l’idée même de rejoindre cette statistique.\n\nJ’ai cru que cette passion suffirait à me faire rebondir, encore et encore, malgré les défis que représente le fait d’être une développeuse — et, dans mon cas, une femme issue de l’immigration.\nMais la réalité est plus complexe.\n\nDans ce talk, je ne parle pas au nom de toutes les femmes. Je partage mon expérience, ma façon de voir les choses, et quelques pistes pour améliorer la rétention des talents féminins dans nos équipes.\n\nVais‑je finir par rejoindre cette statistique ?\nQui sait...",
    dateStartStr: "2026-12-04T13:05:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmpjq82ah007g01mnvcxary56"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
  },
  {
    id: "cmpntx57j00tb01qjcvolkyhb",
    title: "Ethique et Ingéniérie, comment faire?",
    abstract:
      "Les systèmes que nous concevons peuvent influencer des millions de personnes, \nmais il est facile de perdre de vue leur impact sociétal. \n\nComment trouver l'équilibre entre la pression de livrer vite, à la vitesse de l'IA même,\net notre responsabilité envers la société ?\n\nCette conférence s'appuie sur plus de 40 ans d'expérience en génie logiciel, pour\nexplorer des approches concrètes de la prise de décision éthique dans les métiers\ntechniques et plus spécifiquement l'informatique.\n\nJe partagerai des exemples concrets de la façon dont chaque ingénieur-e peut faire\nla différence, avec empathie et persévérance, ainsi que les situations où il est\nplus judicieux de quitter une organisation dont l'éthique\nne nous convient pas.\n\nNous aborderons ces sujets difficiles de manière\npragmatique, pour vous donner des outils concrets dans votre propre situation.\n\nIl n'existe pas de recette magique pour l'ingéniérie éthique, mais vous pouvez\ndévelopper vos propres principes et le courage de les appliquer. Cette présentation\nvous aidera à construire cette démarche, quel que soit votre niveau d'expérience.",
    dateStartStr: "2026-12-04T10:15:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmpntvw1k00t801qj0znd9mkp"],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e101pffzx6q0qu",
  },
  {
    id: "cmpygzsor00qi01ppn58099c8",
    title: "Le typage sous stéroïdes, éviter les erreurs au runtime",
    abstract:
      "Si tu rencontres régulièrement l’erreur `Cannot read properties of undefined`, alors ce talk est fait pour toi.\n\nJavaScript est puissant, flexible… mais dangereusement permissif.\nMême avec TypeScript, certaines erreurs ne se révèlent qu’au runtime.\nRésultat : on empile les if, on abuse de la validation, sans jamais être totalement serein·e·s.\n\nEt si le problème n’était pas le manque de validation mais la façon dont on modélise nos données ?\nDans ce talk, je te propose un changement de perspective :\nPlutôt que vérifier que les données sont valides, faisons en sorte qu’elles ne puissent pas être invalides. Pour ce faire, adaptons la modélisation de notre problème pour réduire la fragilité et le risque d’erreur.\n\nNovices comme expérimenté·e·s, ensemble, voyons comment utiliser des notions de typage avancées pour imposer des contraintes fortes à nos données et détecter les bugs avant le runtime.\nAlors ? Envie de me rejoindre pour écrire du code robuste en live ?",
    dateStartStr: "2026-12-04T15:35:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmpygzsok00qh01pp15pl0dau"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmq6le8a5015201nse3589hw1",
    title:
      "Retour d'expérience : Les coulisses de notre labellisation Numérique Responsable.",
    abstract:
      "On parle beaucoup d'éco-conception logicielle, mais qu'en est-il de la responsabilité globale de nos structures ? À travers notre retour d'expérience concret, découvrez pourquoi et comment décrocher le Label Numérique Responsable (Label NR). Des premières prises de conscience à l'audit final, nous passerons en revue les grandes étapes, les pièges à éviter, ainsi que les formations et certifications indispensables pour transformer l'essai. Venez découvrir l'envers du décor d'une démarche humaine, technique et organisationnelle !",
    dateStartStr: "2026-12-04T15:35:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmq6le89x015101nsin1ha2li"],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00e101pffzx6q0qu",
  },
  {
    id: "cmqajew9m03j501nsrgymvk11",
    title: "Reprenez le contrôle de votre temps ! Pratique délibérée",
    abstract:
      "Vous en avez assez de subir la pression sur votre temps en tant que développeur ? Reprenez-en le contrôle !\n\nQuand on manque de temps pour produire un travail de qualité, on perd l’occasion de se sentir fier de son travail, en sécurité et d’apprendre—et, à long terme, tout le monde perd.\n\nRejoignez notre atelier pour pratiquer une communication assertive et protéger votre temps !\n\nProtégez votre temps et votre équipe :\n\n- Conservez du temps pour les tests et le refactoring, même face à la pression\n- Préservez l’autonomie de votre équipe et du temps pour apprendre\n- Faites un travail de qualité dont vous pouvez être fier\n- Montrez l’exemple et inspirez les autres\n\nCréez un workflow durable :\n\n- Refusez les urgences inutiles et le scope creep\n- Travaillez à un rythme soutenable, sans stress\n- Aidez à prioriser avec des contraintes constructives\n- Adoptez des stratégies gagnant-gagnant pour devs, PMs et organisation\n\nPassez à l’action :\n\n- Entraînez-vous sur des situations concrètes et récurrentes\n- Repartez avec des stratégies constructive pour vous protéger, vous et votre équipe\n\nApprenez en pratiquant dans une session interactive et engageante !",
    dateStartStr: "2026-12-04T13:30:00.000+00:00",
    durationMinutes: 110,
    speakerIds: ["cmqasdxa203pm01ns3eknbn9n", "cmqajew9a03j401nszyd9gmyr"],
    trackId: "jardins-de-la-tour",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00dw01pfktyb71ph",
    categoryId: "cmnd2nkpz00e001pfnbtutqns",
  },
  {
    id: "cmqcd1yv7007z01nlbsgg6s7e",
    title: "Rust pour le développement d'applications métier haut-niveau ! 🦀",
    abstract:
      "Rust est connu pour être un langage très performant, très \"bas niveau\", très ardu à prendre en main, etc.\n\nEt si je vous disais que si tout ça est probablement vrai, ce n'est pas du tout le plus important ? Eh oui, **Rust est selon moi le langage idéal pour développer des applications, parfois de très haut niveau, car il nous donne les moyens de modéliser des domaines métiers avec précision et simplicité**.\n\nParcourons-donc ensemble ce qui fait la richesse \"applicative\" de Rust ! 🦀\n\n- **Un système typal ultra-expressif**, appliqué à des domaines métiers complexes. Voyons comment les Structs, le Pattern Matching et les Traits de Rust le rendent totalement compatible avec des approches haut-niveau comme l'Architecture Hexagonale ou le Domain Driven Design\n- **Un écosystème de librairies applicatives solide, complet, et agréablement documenté**. Venez avec moi parcourir la somptueuse documentation de librairies comme serde, actix-web, ou wiremocks, qui vont vous redonner envie d'écrire de la documentation technique, pour les devs et par les devs\n- **Une manière de tester les applications qui n'a pas son pareil**, et qui complémente superbement le langage afin de vous permettre de développer vos applications avec le meilleur filet de sécurité possible. Tests d'Intégrations, Mocks, Rust a tout du langage de haut-niveau pour délivrer le maximum de valeur.\n\nC'est un tour d'horizon qui changera, j'en suis sûr, votre perception de ce langage qui paraît tellement \"orienté performance et optimisation mémoire\" qu'on en oublie que c'est avant tout un langage très expressif.\n\nEt même si vous n'écrirez jamais une ligne de Rust, cette conférence devrait vous donner pas mal de tuyaux sur l'écriture moderne d'applications et ce qu'on est en droit d'attendre de nos écosystèmes de développement 😉",
    dateStartStr: "2026-12-04T11:10:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmqcd16ik007w01nl6jz56z49"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00dy01pffvvmj12s",
  },
  {
    id: "cmqdezxnz000g01qh1a8rsj0q",
    title:
      "Arrêtez de deviner, regardez votre code vivre - L'observabilité en continu avec OpenTelemetry",
    abstract:
      "Nous connaissons notre code en détail, mais **beaucoup moins son comportement réel une fois en production**.\n\nQuand une application ralentit, consomme plus de mémoire ou se comporte différemment, une question revient toujours : est-ce normal ?\nFace à ces situations, nous réagissons souvent de la même manière : ajouter des logs, augmenter les ressources, redéployer, tester des hypothèses. Pourtant, avant de corriger un problème, encore faut-il comprendre ce qui se passe réellement. C'est précisément le rôle de l'observabilité : rendre visible le comportement interne d'un système à partir de ce qu'il expose, pour passer de l'intuition à la compréhension. \n\nMais une métrique seule ne dit rien. Une latence à 300 ms, est-ce inquiétant ? Sans référence, impossible de distinguer une anomalie d'un comportement attendu. **Cette référence transforme un signal brut en information exploitable**. Et elle ne se construit pas au moment où un incident survient : elle s'apprend progressivement, dès les premières phases de développement, de test et de recette.\n**Plus tôt l'observabilité devient accessible, plus il devient possible de comprendre le comportement nominal** avant que les problèmes apparaissent. \n\nDans ce retour d'expérience chez Atol CD, nous verrons ce qui a été mis en place pour rendre cette compréhension disponible par défaut dans un contexte bien réel : multi-équipes, multi-technologies, nombreux projets, le tout avec des composants open source auto-hébergés.\n**L'objectif n'est pas de produire davantage de données, mais de construire une baseline fiable et la rendre disponible en supprimant au maximum la friction côté développeur.**\n\nAu-delà des outils, nous reviendrons sur les **choix structurants et les difficultés rencontrées** : comment standardiser des données provenant de technologies différentes, éviter les dashboards jetables, construire des conventions qui tiennent dans le temps ou encore rendre une stack mutualisée réellement simple à adopter.\nAvec démonstrations et exemples concrets à l'appui, nous verrons autant ce qui a fonctionné que ce qui ne s'improvise pas.\n\nParce que le vrai défi n'est pas de produire plus de données d'observabilité. C'est d'arrêter de deviner.",
    dateStartStr: "2026-12-04T11:10:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmqdezxni000f01qhq5gy12r9"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmqeyn80f00cp01qf1kkt1h53",
    title: "Let's play Factorio",
    abstract:
      "Factorio est un jeu vidéo d'automatisation hautement addictif (croyez-en mes 300h de jeu).\n\nLe but est simple : le vaisseau spatial du joueur est échoué sur une planète extra-terrestre, il faut construire une fusée pour s'échapper, en utilisant toutes les ressources disponibles sur la planète.\nLe joueur construit alors une usine (d'où le nom du jeu) pour créer des matériaux de plus en plus complexes, jusqu'à pouvoir construire la fusée salvatrice.\n\nMais quel rapport avec la tech ?\n\nArchitectures de code spaghetti, lasagna ou ravioli (mes préférés). Urbanisation et ESB. Métriques, alertes, root-cause analysis. Scalabilité horizontale, verticale, load-balancing. Charge, débit, performance. Sécurité, firewalls, DDoS.\n\nOn peut retrouver tous ces concepts dans le jeu.\n\nCe talk, intégralement réalisé dans le jeu, reprend et illustre ces différents concepts qui sont au cœur de nos métiers. \nPour les débutants, ce sera l'occasion de comprendre ces concepts fondamentaux.\nPour les plus expérimentés, ce sera l'occasion de les voir illustrés en dehors d'un schéma d'architecture ennuyeux.\n\nThe Factory Must Grow 🏭⚙️",
    dateStartStr: "2026-12-04T14:25:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmqeyn80600co01qfeaaqnavi"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e201pflsbqsosg",
  },
  {
    id: "cmqkogjdg057701qfcicdulsb",
    title: "SELECT 'amazing_features' FROM \"posgresql\"",
    abstract:
      'C\'est unanime, `PostgreSQL` devient le Linux de la base de données pour le bien de tous 🚀!\nEt cela parce que ce moteur de BDD contient des fonctionnalités fantastiques permettant de résoudre des problèmes complexes très simplement!\n\n<img src="https://link.davinkevin.fr/pgfeatures-cover" alt="drawing" width="200"/>\n\nVenez découvrir dans cette présentation les features les plus utiles et pratiques pour vous éviter de tout re-coder "from scratch" 😅!\nL\'on détaillera des features standards du monde SQL trop peu connues et des features propres à PG qui en font un moteur SQL passionnant 🔥\n\nEt pour terminer, l\'on fera le tour des "distributions" `PostgreSQL` disponibles, car dans ce domaine, il y a beaucoup de choix, pour de l\'on-prem ou dans le cloud ☁️',
    dateStartStr: "2026-12-04T09:05:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmqkodgg6056q01qfly5vf43y"],
    trackId: "forge",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00dy01pffvvmj12s",
  },
  {
    id: "cmquokspe03a001kxah1w6yks",
    title: "Containeriser vos applications PHP avec FrankenPHP !",
    abstract:
      "Avez-vous déjà essayé de containeriser une application PHP ?\n\nTraditionnellement, pour mettre en place un site web en PHP, nous utilisons un serveur web comme Apache ou nginx, ainsi qu’un serveur d’application comme PHP-FPM. C’est très simple ! Mais dès qu’on veut le faire de manière containerisée, c’est une autre galère !\n\nDans ce talk, j’expliquerai les difficultés que j’ai eues à containeriser un Drupal et comment j’ai résolu cela avec FrankenPHP.",
    dateStartStr: "2026-12-04T15:35:00.000+00:00",
    durationMinutes: 20,
    speakerIds: ["cmquoksp4039z01kx54gm57g9"],
    trackId: "tour-des-arcanes",
    language: "fr",
    level: "INTERMEDIATE",
    formatId: "cmnd2nkpn00dv01pfj5fi0f0s",
    categoryId: "cmnd2nkpz00dz01pf4xodlt41",
  },
  {
    id: "cmr0tifwn06kc01kxaaq4popo",
    title: "L'écoconception numérique sans bullshit",
    abstract:
      '_"Quel langage de programmation consomme le moins d\'énergie ?" "Comment mesurer la consommation d\'électricité de son code backend ?" "Comment analyser son code dans sa CI pour éviter les mauvais patterns et le rendre plus green ?" "Estimez les émissions carbone de votre site avec co2.js"_ **— STOOOOP !!!! — bullshit alarm 🚨 —** Partons de la définition de l\'écoconception, appliquons-là au numérique, regardons les chiffres, passons par le RGESN et les Web Sustainability Guidelines du W3C, et on saura déterminer nos priorités pour réellement améliorer l\'empreinte environnementale de nos applications.',
    dateStartStr: "2026-12-04T09:05:00.000+00:00",
    durationMinutes: 50,
    speakerIds: ["cmr0tifwd06kb01kxnq4re7ny"],
    trackId: "scriptorium",
    language: "fr",
    level: "BEGINNER",
    formatId: "cmnd2nkpn00du01pf943n1bfc",
    categoryId: "cmnd2nkpz00e101pffzx6q0qu",
  },
];
